sudo: required

language: csharp

cache:
  directories:
    - packages

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in dockerKey.enc -out dockerKey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 dockerKey
  - ssh-add dockerKey

script:
  - docker build -t webapp:test -f ./dockerfile/test .
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
  
after_success:
  - sudo docker build -t webapp:release -f ./dockerfile/release .
  - docker tag webapp:release thuranel/webapp:release
  - docker login -u=thuranel -p=$mdp_docker_hub
  - docker push thuranel/webapp:release
  - scp -o StrictHostKeyChecking=no ./scripts/getReleaseFromDockerHubAndStart.sh u1432676@159.203.33.172:~/
  - ssh u1432676@159.203.33.172 "chmod +x getReleaseFromDockerHubAndStart.sh"
  - ssh u1432676@159.203.33.172 "sh getReleaseFromDockerHubAndStart.sh"
  